application: food-cart
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /static
  static_dir: static

- url: /.*
  script: food_cart.app
